In [2]:
import numpy as np



---


Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули.





In [ ]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])



---


Создайте двумерный массив 10x3, 
заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [ ]:
a = np.random.random((10, 3))
print (a)
np.amin(np.abs(a - 0.5), axis = 1)+0.5


[[0.76918849 0.57817596 0.09329549]
 [0.23991281 0.83055752 0.66311445]
 [0.04407759 0.57297352 0.17561803]
 [0.63866647 0.31786282 0.54835194]
 [0.85649129 0.59329154 0.39723054]
 [0.04561434 0.07526646 0.27130356]
 [0.81715315 0.97334068 0.92669647]
 [0.44601525 0.6899055  0.31108172]
 [0.9999036  0.6811919  0.7259552 ]
 [0.75004377 0.32050067 0.13724695]]


array([0.57817596, 0.66311445, 0.57297352, 0.54835194, 0.59329154,
       0.72869644, 0.81715315, 0.55398475, 0.6811919 , 0.67949933])



---

Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [ ]:
a = np.random.random((6, 6))
np.sum(a, axis = 1) / np.amax(a, axis=1)

array([2.88851528, 2.63442859, 2.70281244, 3.64565201, 3.28585434,
       3.57068167])



---

На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.



In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = x == 0


array([0, 0, 0, 0])



---

Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [ ]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for arg in i:
    x[arg]+=1
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])



---

Сколько вы можете предложить способов округлить значения в массиве до ближайшего целого?

In [25]:
a = 10* np.random.random((6, 6))
print (a)
print(np.round_(a))
print(np.around(a))
print((a+ 0.5).astype(np.int64))


[[0.27893037 1.95111301 7.72239905 4.70929937 8.56641941 7.89089332]
 [4.80636079 4.09635258 2.867006   1.78452971 8.9736935  4.74151943]
 [8.27335084 1.72208828 3.20187967 7.3503719  4.50507959 8.77857405]
 [0.55760797 5.58790004 8.76563209 3.83171414 4.94633848 1.71996404]
 [2.68924364 4.13682398 5.81556329 8.08570352 4.37503954 1.3517878 ]
 [7.46074535 2.7792028  9.29754507 4.0540252  1.93495187 8.11208526]]
[[0. 2. 8. 5. 9. 8.]
 [5. 4. 3. 2. 9. 5.]
 [8. 2. 3. 7. 5. 9.]
 [1. 6. 9. 4. 5. 2.]
 [3. 4. 6. 8. 4. 1.]
 [7. 3. 9. 4. 2. 8.]]
[[0. 2. 8. 5. 9. 8.]
 [5. 4. 3. 2. 9. 5.]
 [8. 2. 3. 7. 5. 9.]
 [1. 6. 9. 4. 5. 2.]
 [3. 4. 6. 8. 4. 1.]
 [7. 3. 9. 4. 2. 8.]]
[[0 2 8 5 9 8]
 [5 4 3 2 9 5]
 [8 2 3 7 5 9]
 [1 6 9 4 5 2]
 [3 4 6 8 4 1]
 [7 3 9 4 2 8]]




---

Написать функцию, реализующую алгоритм k-means.

Входом в функцию является

массив NxM, где N - число объектов, M - число признаков объекта
k - число кластеров
max_iter - максимальное число итераций
theshold - критерий остановки (если на очередной итерации метода суммарное квадратичное отклонение изменяется меньше, чем на theshold, итерации прекращаются)
Выход:

массив длины N, содержащий индексы кластеров от 0 до k-1
суммарное квадратичное отклонение для полученного разбиения на кластеры
Фунция должна содержать не более 2 циклов for/while! Стремитесь обойтись как можно меньшим количеством строк кода.

Примечание: алгоритм может работать долго из-за того, что долго происходит выделение памяти под большие массивы. С точки зрения эффективности - это плохой пример, но целью задания является написание не самого быстрого, а самого компактного алгоритма.



---

Выделить кластеры в датасете MNIST:
Сперва попробуйте K=10. Дайте интерпретацию каждому полученному кластеру (к какой цифре его можно отнести). Нарисуйте изображения, которые отвечают центрам кластеров. Посчитайте, сколько из точек кластера действительно являются той цифрой, к которой вы его отнесли (для этого сравните с массивом правильных ответов labels)
Попробуйте подобрать оптимальное число кластеров методом elbow (можно предположить, что некоторые цифры распадаются на несколько кластеров, например, 7 можно писать с черточкой и без и т.д.)
Примечание: можно уменьшить размер выборки MNIST, например, до 10К, чтобы алгоритм работал быстрее.